package:
  name: petsc
  version: "3.6.2"

source:
  fn: petsc-lite-3.6.2.tar.gz
  url: http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-lite-3.6.2.tar.gz
  md5: 5b6b7129ba02f4c6d107ae7671b80bb8

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - mpi4py

  run:
    - python
    - mpi4py

test:
  requires:
    #- gcc

about:
  home: http://www.mcs.anl.gov/petsc/
  license: PETSc
  summary: 'PETSc: Portable, Extensible Toolkit for Scientific Computation'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
