package:
  name: h5py
  version: "2.6.0"

source:
  fn: 2.6.0.tar.gz
  url: https://github.com/h5py/h5py/archive/2.6.0.tar.gz
  md5: 613c5776192eaf02ff96a82dfc6d2e78

build:
  number: 6

requirements:
  build:
    - python
    - numpy
    - cython
    - mpi4py
    - six
    - gcc
    - pkgconfig
    - hdf5 ==1.8.14

  run:
    - python
    - numpy
    - mpi4py
    - hdf5 ==1.8.14
    - six

test:
  imports:
    - h5py
