package:
  name: ffc
  #version: "1.6.0"
  version: "1.7.0"

source:
  #fn: ffc-1.6.0.tar.gz
  #url: https://bitbucket.org/fenics-project/ffc/downloads/ffc-1.6.0.tar.gz
  #md5: 358faa3e9da62a1b1a717070217b793e
  git_url: https://bitbucket.org/fenics-project/ffc
  git_tag: master 

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    - numpy 
    - swig

  run:
    - python
    - numpy
    - swig
    - ufl ==1.7.0
    - fiat ==1.7.0
    - instant ==1.7.0

test:
  imports:
    - ffc
    - ffc.backends
    - ffc.backends.dolfin
    - ffc.backends.ufc
    - ffc.errorcontrol
    - ffc.quadrature
    - ffc.tensor
    #- ffc_time_ext.time_elements_ext  # See #47
    - ufc

  commands:
    - ffc --help

about:
  home: http://fenicsproject.org/
  license: The GNU Lesser General Public License, version 3.0
  summary: 'The FEniCS Form Compiler'

