package:
  name: petsc4py
  version: "3.6.0"

source:
  fn: petsc4py-3.6.0.tar.gz
  url: https://bitbucket.org/petsc/petsc4py/downloads/petsc4py-3.6.0.tar.gz
  md5: e63a8e30318b5de9ffb081832e9daf30

build:
  number: 3

requirements:
  build:
    - python
    - openblas
    - numpy
    - petsc ==3.6.2

  run:
    - python
    - openblas
    - numpy
    - petsc ==3.6.2

test:
  imports:
    - petsc4py
    - petsc4py.lib

about:
  home: https://bitbucket.org/petsc/petsc4py/
  license: BSD License
  summary: 'PETSc for Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
