package:
  name: slepc
  version: "3.6.2"

source:
  git_rev: e878de6
  git_url: https://bitbucket.org/slepc/slepc.git

build:
  number: 3

requirements:
  build:
    - python
    - gcc
    - petsc <=3.6.2

  run:
    - python
    - libgcc
    - petsc <=3.6.2

test:
  requires:
    - gcc

about:
  home: http://www.grycap.upv.es/slepc/
  license: GNU Library or Lesser General Public License (LGPL)
  summary: 'SLEPc: Scalable Library for Eigenvalue Problem Computations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
