package:
  name: dolfin
  version: {{FENICS_VERSION}}

source:
  git_url: https://bitbucket.org/fenics-project/dolfin
  git_tag: master 
  #git_tag: dolfin-{{FENICS_GIT_TAG}}

build:
  number: {{CONDA_BUILD_NUMBER}}

requirements:
  build:
    - python
    #- eigen3
    - sphinx
    - swig 
    - numpy
    - ffc =={{FENICS_VERSION}}
    - ply ==3.8

  run:
    - python
    #- eigen3
    - swig
    - numpy
    - ffc =={{FENICS_VERSION}}
    - ufl =={{FENICS_VERSION}}
    - ply ==3.8

test:
  imports:
    - dolfin

about:
  home: http://www.fenicsproject.org
  license: The GNU Lesser General Public License, version 3.0
  summary: 'C++/Python library for solving differential equations'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
